/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD2_PF;

import TD2_PF.td2_universite.Annee;
import TD2_PF.td2_universite.Etudiant;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;

public class App {
    //Exercice 1

    //Question 1
    public static void question1(){
        Somme<Integer> integerSomme = (x,y) -> x+y;
        Somme<Long> longSomme = (x,y) -> x+y;
        Somme<Double> doubleSomme = (x,y) -> x+y;
        Somme<String> stringSomme = (x,y) -> x+y;

        System.out.println(integerSomme.somme(1,2));
        System.out.println(longSomme.somme(1L,2L));
        System.out.println(doubleSomme.somme(1.5,2.10));
        System.out.println(stringSomme.somme("to","to"));

    }

    public static void question2() {
        List<String> list2string = List.of("a", "b", "c", "d");
        ToString<List<String>> l2s = list -> {
            StringBuffer chaine = new StringBuffer();
            boolean isPremier = true;
            for (String e : list) {
                if (!isPremier)
                    chaine.append(",");
                else
                    isPremier = false;
                chaine.append(e);
            }
            return chaine.toString();
        };

        System.out.println(l2s.conversion(list2string));
    }

    //Exercice 2

    public static void question2_1(){
        Predicate<Integer> tropPetit = x -> x<100;
        Predicate<Integer> tropGrand = x -> x>200;
        Predicate<Integer> mauvaiseTaille = tropPetit.or(tropGrand);
        Predicate<Integer> tailleCorrecte = mauvaiseTaille.negate();
        Predicate<Double> tropLourd = x -> x>150.0;
        Predicate<Double> poidsCorrect = tropLourd.negate();
        Predicate<Paire<Integer,Double>> autorise = x -> tailleCorrecte.test(x.fst) && poidsCorrect.test(x.snd);

    }

    public static <T> List<T> filtragePredicatif(List<Predicate<T>> predicats, List<T> list){
        List<T> res = new ArrayList<T>();
        Predicate<T> predicate = x -> true;
        for(Predicate<T> i : predicats){
            predicate = predicate.and(i);
        }
        for(T elt : list){
            if(predicate.test(elt)){
                res.add(elt);
            }
        }

        return res;
    }

    public static void question2_2(){
        Predicate<Integer> tropPetit = x -> x<100;
        Predicate<Integer> tropGrand = x -> x>200;
        Predicate<Integer> mauvaiseTaille = tropPetit.or(tropGrand);
        Predicate<Integer> tailleCorrecte = mauvaiseTaille.negate();
        Predicate<Double> tropLourd = x -> x>150.0;
        Predicate<Double> poidsCorrect = tropLourd.negate();
        Predicate<Paire<Integer,Double>> autorise = x -> tailleCorrecte.test(x.fst) && poidsCorrect.test(x.snd);

        Predicate<Paire<Integer,Double>> tropPetitv2 = x -> x.fst<100;
        Predicate<Paire<Integer,Double>> tropGrandv2 = x -> x.fst>200;
        Predicate<Paire<Integer,Double>> mauvaiseTaillev2 = tropPetitv2.or(tropGrandv2);
        Predicate<Paire<Integer,Double>> tailleCorrectev2 = mauvaiseTaillev2.negate();
        Predicate<Paire<Integer,Double>> tropLourdv2 = x -> x.snd>150.0;
        Predicate<Paire<Integer,Double>> poidsCorrectev2 = tropLourdv2.negate();
        Predicate<Paire<Integer,Double>> autorisev2 = tailleCorrectev2.and(poidsCorrectev2);

        List<Paire<Integer,Double>> maList = List.of(
                new Paire<Integer,Double>(1,50.0),
                new Paire<Integer, Double>(201,40.5),
                new Paire<Integer, Double>(180,180.0),
                new Paire<Integer, Double>(160, 300.0)
        );

        List<Predicate<Paire<Integer,Double>>> conditions= List.of(tailleCorrectev2);
        filtragePredicatif(conditions,maList);
    }

    //Exercice 3
    public static void afficheSi(String entete, Predicate<Etudiant> predicate, Annee a) {
        System.out.println(String.format("\n**%s\n", entete));
        a.getEtudiants().forEach(e -> {
            if (predicate.test(e))
                System.out.println(e.getNom());
        });
    }


}
